backend:
  name: git-gateway
  branch: main
  # Ohne spezifische URLs verwendet Netlify automatisch die aktuelle Domain

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "seo_settings"
    label: "SEO Einstellungen"
    files:
      - label: "Startseite SEO"
        name: "home_seo"
        file: "src/content/seo/home.md"
        fields:
          - { label: "Meta Titel", name: "title", widget: "string", default: "Kira Marie - Leadership & Vertrauensexpertin | Executive Coach, Speakerin, Autorin" }
          - { label: "Meta Beschreibung", name: "description", widget: "text", default: "Kira Marie ist Ihre Expertin für Leadership und Vertrauen. Als Executive Coach, Speakerin und Autorin unterstützt sie Führungskräfte und Unternehmen auf dem Weg zu nachhaltigem Erfolg und starker Führungskultur." }
          - { label: "Social Media Bild (OG Image)", name: "og_image", widget: "image", required: false, hint: "Empfohlene Größe: 1200x630 Pixel" }
      - label: "Funke Feed SEO"
        name: "funke_feed_seo"
        file: "src/content/seo/funke-feed.md"
        fields:
          - { label: "Meta Titel", name: "title", widget: "string", default: "Aktuelle Beiträge von Kira Marie bei Funke - Kira Marie" }
          - { label: "Meta Beschreibung", name: "description", widget: "text", default: "Entdecken Sie die neuesten Artikel, Kolumnen und Beiträge von Kira Marie, veröffentlicht bei der Funke Mediengruppe." }
          - { label: "Social Media Bild (OG Image)", name: "og_image", widget: "image", required: false, hint: "Empfohlene Größe: 1200x630 Pixel" }

  - name: "social_stats"
    label: "Social Media Zahlen"
    files:
      - label: "Follower Zahlen"
        name: "follower_counts"
        file: "src/content/social_stats.json"
        fields:
          - label: "Plattformen"
            name: "platforms"
            widget: "list"
            summary: "{{fields.name}}: {{fields.count}}"
            min: 3
            max: 3
            fields:
              - { label: "Name", name: "name", widget: "select", options: ["LinkedIn", "Instagram", "Spotify"], default: "LinkedIn" }
              - { label: "Follower Anzahl", name: "count", widget: "number" }
              - { label: "Profil URL", name: "url", widget: "string" }

  - name: "press"
    label: "Presse-Einträge"
    folder: "src/content/press"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publikation", name: "publication", widget: "string" }
      - { label: "Link zum Artikel", name: "url", widget: "string" }
      - { label: "Auszug/Zitat", name: "excerpt", widget: "markdown" }
      - { label: "Bild (optional)", name: "image", widget: "image", optional: true }

  - name: "about_page"
    label: "Über Mich Seite"
    files:
      - label: "Über Mich Seite"
        name: "about_page"
        file: "src/content/about.md"
        fields:
          - { label: "Seitentitel (für Browser/SEO)", name: "page_title", widget: "string", default: "Über Mich", required: false }
          - { label: "Name (für Tag & Überschrift)", name: "name_for_tag_and_headline", widget: "string", default: "Kira Marie Cremer" }
          - { label: "Haupttext der Überschrift (nach Name)", name: "headline_main_text", widget: "text", default: "ist eine der führenden deutschen Stimmen im Bereich New Work und Expertin für die Zukunft der Arbeitswelt." }
          - { label: "Profilbild (Hauptbild)", name: "profile_image", widget: "image", required: false }
          - { label: "Bild 1 (Linke Spalte oben)", name: "left_image_1", widget: "image", required: false }
          - { label: "Bild 2 (Linke Spalte unten)", name: "left_image_2", widget: "image", required: false }
          - { label: "Bild 3 (Rechte Spalte)", name: "right_image", widget: "image", required: false }
          - { label: "Biografie / Haupttext", name: "body", widget: "markdown" }

  - name: "testimonials"
    label: "Kundenstimmen / Testimonials"
    folder: "src/content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Zitat Geber (Name)", name: "author", widget: "string" }
      - { label: "Position / Firma (optional)", name: "position", widget: "string", required: false }
      - { label: "Zitat", name: "quote", widget: "markdown" }
      - { label: "Bild (optional, z.B. Avatar oder Logo)", name: "image", widget: "image", required: false }
      - { label: "Reihenfolge (optional, niedrigere Zahlen zuerst)", name: "order", widget: "number", required: false, default: 100 }

  - name: "partner_logos"
    label: "Partner Logos (Hero Section)"
    label_singular: "Partner Logo"
    folder: "src/content/partner_logos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name des Partners", name: "name", widget: "string" }
      - { label: "Logo Bild", name: "image", widget: "image" }
      - { label: "Alt-Text für Bild", name: "alt_text", widget: "string" }
      - { label: "Reihenfolge (für Anzeige)", name: "order", widget: "number", value_type: "int", default: 100, required: false }

  - name: "podcast_episodes"
    label: "Podcast Episoden"
    label_singular: "Podcast Episode"
    description: "Verwaltung der Podcast Episoden für die 'Neueste Folgen' Sektion."
    files:
      - name: "all_podcast_episodes_file"
        label: "Alle Podcast Episoden"
        file: "public/data/podcastEpisodes.json"
        editor:
          preview: false
        fields:
          - name: "all_episodes"
            label: "Episoden Liste"
            widget: "list"
            add_to_top: true
            label_singular: "Neue Episode hinzufügen"
            summary: "{{fields.title}} | {{fields.date}}"
            fields:
              - { label: "ID", name: "id", widget: "string", hint: "Eindeutige ID, z.B. podcast-143. Muss manuell vergeben werden." }
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Datum", name: "date", widget: "string", hint: "Format: TT.MM.JJJJ (z.B. 20.05.2025)" }
              - { label: "Dauer", name: "duration", widget: "string", hint: "z.B. 41 Minuten" }
              - { label: "Beschreibung", name: "description", widget: "text" }
              - { label: "Bild", name: "imageUrl", widget: "image", hint: "Podcast Episodenbild. Wird in /public/uploads gespeichert." }
              - { label: "Alternativtext für Bild", name: "altText", widget: "string", hint: "Kurze Beschreibung des Bildes für Barrierefreiheit." }

  - name: "whatthework_about"
    label: "WHAT THE WORK?! - Über Mich"
    files:
      - label: "Inhalte der 'Über Mich' Sektion auf WHAT THE WORK?!"
        name: "whatthework_about_content"
        file: "src/content/whatthework-about.md"
        fields:
          - { label: "Headline", name: "headline", widget: "string", default: "Das ist WHAT THE WORK?!" }
          - { label: "Sub-Headline", name: "subHeadline", widget: "string", required: false }
          - { label: "Text", name: "text", widget: "markdown" }
          - { label: "Bild", name: "image", widget: "image", required: false }
          - { label: "Button Text", name: "buttonText", widget: "string", required: false }
          - { label: "Button Link (URL)", name: "buttonLink", widget: "string", required: false }

  - name: "whatthework_testimonials"
    label: "WHAT THE WORK?! - Testimonials"
    description: "Verwaltung der Testimonials für die WHAT THE WORK?! Seite."
    files:
      - name: "all_whatthework_testimonials_file"
        label: "Alle WHAT THE WORK?! Testimonials"
        file: "public/data/whattheworkTestimonialsData.json"
        editor:
          preview: false
        fields:
          - name: "testimonials" 
            label: "Testimonial Liste"
            widget: "list"
            add_to_top: false
            label_singular: "Neues Testimonial hinzufügen"
            summary: "{{fields.author}}: {{fields.quote | truncate(50, \"...\")}}"
            fields:
              - { label: "Zitat Geber (Name)", name: "author", widget: "string" }
              - { label: "Position / Firma (optional)", name: "position", widget: "string", required: false }
              - { label: "Zitat", name: "quote", widget: "markdown" }
              - { label: "Bild (optional)", name: "image", widget: "image", required: false }
              - { label: "Reihenfolge (optional, niedrigere Zahlen zuerst)", name: "order", widget: "number", required: false, default: 100 }