backend:
  name: git-gateway
  branch: main # Oder dein primärer Branch (z.B. master)
  identity_url: "https://kiramarie.netlify.app/.netlify/identity"
  gateway_url: "https://kiramarie.netlify.app/.netlify/git"

# Vorherige lokale Konfiguration (zur Referenz):
# backend:
#   name: test-repo
#   local_backend: true

media_folder: "public/uploads" # Wo hochgeladene Bilder gespeichert werden (relativ zum Projektstamm)
public_folder: "/uploads"     # Der öffentliche Pfad zu den Bildern (wie im Browser aufgerufen)

collections:
  - name: "social_stats"
    label: "Social Media Zahlen"
    files:
      - label: "Follower Zahlen"
        name: "follower_counts"
        file: "src/content/social_stats.json"
        fields:
          - label: "Plattformen"
            name: "platforms"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Follower Anzahl", name: "count", widget: "number" }
              - { label: "Profil URL", name: "url", widget: "string" }

  - name: "press"
    label: "Presse-Einträge"
    folder: "src/content/press"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publikation", name: "publication", widget: "string" }
      - { label: "Veröffentlichungsdatum", name: "date", widget: "date" }
      - { label: "Link zum Artikel", name: "url", widget: "string" }
      - { label: "Auszug/Zitat", name: "excerpt", widget: "markdown" }
      - { label: "Bild (optional)", name: "image", widget: "image", optional: true }

  - name: "about_page"
    label: "Über Mich Seite"
    files:
      - label: "Über Mich Seite"
        name: "about_page"
        file: "src/content/about.md" # Einzelne Markdown-Datei für die "Über Mich"-Inhalte
        fields:
          - { label: "Seitentitel (für Browser/SEO)", name: "page_title", widget: "string", default: "Über Mich", required: false }
          - { label: "Name (für Tag & Überschrift)", name: "name_for_tag_and_headline", widget: "string", default: "Kira Marie Cremer" }
          - { label: "Haupttext der Überschrift (nach Name)", name: "headline_main_text", widget: "text", default: "ist eine der führenden deutschen Stimmen im Bereich New Work und Expertin für die Zukunft der Arbeitswelt." }
          - { label: "Profilbild", name: "profile_image", widget: "image", required: false }
          - { label: "Biografie / Haupttext", name: "bio", widget: "markdown" }