backend:
  name: git-gateway
  branch: main
  identity_url: "https://kiramarie.netlify.app/.netlify/identity"
  gateway_url: "https://kiramarie.netlify.app/.netlify/git"

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "seo_settings"
    label: "SEO Einstellungen"
    files:
      - label: "Startseite SEO"
        name: "home_seo"
        file: "src/content/seo/home.md"
        fields:
          - { label: "Meta Titel", name: "title", widget: "string", default: "Kira Marie - Leadership & Vertrauensexpertin | Executive Coach, Speakerin, Autorin" }
          - { label: "Meta Beschreibung", name: "description", widget: "text", default: "Kira Marie ist Ihre Expertin für Leadership und Vertrauen. Als Executive Coach, Speakerin und Autorin unterstützt sie Führungskräfte und Unternehmen auf dem Weg zu nachhaltigem Erfolg und starker Führungskultur." }
          - { label: "Social Media Bild (OG Image)", name: "og_image", widget: "image", required: false, hint: "Empfohlene Größe: 1200x630 Pixel" }
      - label: "Funke Feed SEO"
        name: "funke_feed_seo"
        file: "src/content/seo/funke-feed.md"
        fields:
          - { label: "Meta Titel", name: "title", widget: "string", default: "Aktuelle Beiträge von Kira Marie bei Funke - Kira Marie" }
          - { label: "Meta Beschreibung", name: "description", widget: "text", default: "Entdecken Sie die neuesten Artikel, Kolumnen und Beiträge von Kira Marie, veröffentlicht bei der Funke Mediengruppe." }
          - { label: "Social Media Bild (OG Image)", name: "og_image", widget: "image", required: false, hint: "Empfohlene Größe: 1200x630 Pixel" }

  - name: "social_stats"
    label: "Social Media Zahlen"
    files:
      - label: "Follower Zahlen"
        name: "follower_counts"
        file: "src/content/social_stats.json"
        fields:
          - label: "Plattformen"
            name: "platforms"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Follower Anzahl", name: "count", widget: "number" }
              - { label: "Profil URL", name: "url", widget: "string" }

  - name: "press"
    label: "Presse-Einträge"
    folder: "src/content/press"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publikation", name: "publication", widget: "string" }
      - { label: "Veröffentlichungsdatum", name: "date", widget: "date" }
      - { label: "Link zum Artikel", name: "url", widget: "string" }
      - { label: "Auszug/Zitat", name: "excerpt", widget: "markdown" }
      - { label: "Bild (optional)", name: "image", widget: "image", optional: true }

  - name: "about_page"
    label: "Über Mich Seite"
    files:
      - label: "Über Mich Seite"
        name: "about_page"
        file: "src/content/about.md"
        fields:
          - { label: "Seitentitel (für Browser/SEO)", name: "page_title", widget: "string", default: "Über Mich", required: false }
          - { label: "Name (für Tag & Überschrift)", name: "name_for_tag_and_headline", widget: "string", default: "Kira Marie Cremer" }
          - { label: "Haupttext der Überschrift (nach Name)", name: "headline_main_text", widget: "text", default: "ist eine der führenden deutschen Stimmen im Bereich New Work und Expertin für die Zukunft der Arbeitswelt." }
          - { label: "Profilbild", name: "profile_image", widget: "image", required: false }
          - { label: "Biografie / Haupttext", name: "body", widget: "markdown" }

  - name: "testimonials"
    label: "Kundenstimmen / Testimonials"
    folder: "src/content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Zitat Geber (Name)", name: "author", widget: "string" }
      - { label: "Position / Firma (optional)", name: "position", widget: "string", required: false }
      - { label: "Zitat", name: "quote", widget: "markdown" }
      - { label: "Bild (optional, z.B. Avatar oder Logo)", name: "image", widget: "image", required: false }
      - { label: "Reihenfolge (optional, niedrigere Zahlen zuerst)", name: "order", widget: "number", required: false, default: 100 }

  - name: "partner_logos"
    label: "Partner Logos (Hero Section)"
    label_singular: "Partner Logo"
    folder: "src/content/partner_logos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name des Partners", name: "name", widget: "string" }
      - { label: "Logo Bild", name: "image", widget: "image" }
      - { label: "Alt-Text für Bild", name: "alt_text", widget: "string" }
      - { label: "Reihenfolge (für Anzeige)", name: "order", widget: "number", value_type: "int", default: 100, required: false }