backend:
  name: git-gateway
  branch: main # Oder dein primärer Branch (z.B. master)
  identity_url: "https://kiramarie.netlify.app/.netlify/identity"
  gateway_url: "https://kiramarie.netlify.app/.netlify/git"

# Vorherige lokale Konfiguration (zur Referenz):
# backend:
#   name: test-repo
#   local_backend: true

media_folder: "public/uploads" # Wo hochgeladene Bilder gespeichert werden (relativ zum Projektstamm)
public_folder: "/uploads"     # Der öffentliche Pfad zu den Bildern (wie im Browser aufgerufen)

collections:
  - name: "pages"
    label: "Seiten-Texte"
    files:
      - label: "About Seite"
        name: "about"
        file: "src/content/about.md" # Pfad zur Datei, die die Inhalte speichert (relativ zum Projektstamm)
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Einleitungstext", name: "introduction", widget: "markdown" }
          - { label: "Hauptinhalt", name: "body", widget: "markdown" }

  - name: "social_stats"
    label: "Social Media Zahlen"
    files:
      - label: "Follower Zahlen"
        name: "follower_counts"
        file: "src/content/social_stats.json"
        fields:
          - label: "Plattformen"
            name: "platforms"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Follower Anzahl", name: "count", widget: "number" }
              - { label: "Profil URL", name: "url", widget: "string" }

  - name: "press"
    label: "Presse-Einträge"
    folder: "src/content/press"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publikation", name: "publication", widget: "string" }
      - { label: "Veröffentlichungsdatum", name: "date", widget: "date" }
      - { label: "Link zum Artikel", name: "url", widget: "string" }
      - { label: "Auszug/Zitat", name: "excerpt", widget: "markdown" }
      - { label: "Bild (optional)", name: "image", widget: "image", optional: true }

  - name: "about_page"
    label: "Über Mich Seite"
    files:
      - label: "Über Mich Seite"
        name: "about_page"
        file: "src/content/about.md" # Einzelne Markdown-Datei für die "Über Mich"-Inhalte
        fields:
          - { label: "Seitentitel", name: "title", widget: "string", default: "Über Mich", required: false }
          - { label: "Hauptüberschrift", name: "headline", widget: "string", default: "Kira Marie Born" }
          - { label: "Unterüberschrift / Motto", name: "subheadline", widget: "string", required: false }
          - { label: "Profilbild", name: "profile_image", widget: "image", required: false }
          - { label: "Biografie / Haupttext", name: "bio", widget: "markdown" }
          - label: "Expertise Tags"
            name: "expertise_tags"
            widget: "list"
            summary: "{{fields.tag}}"
            field: { label: "Tag", name: "tag", widget: "string" }
          - label: "Statistiken"
            name: "stats"
            widget: "list"
            summary: "{{fields.value}} {{fields.label}}"
            fields:
              - { label: "Wert (z.B. '5+' oder '100')", name: "value", widget: "string" }
              - { label: "Bezeichnung (z.B. 'Jahre Erfahrung')", name: "label", widget: "string" }
          - { label: "CTA Button Text", name: "cta_button_text", widget: "string", required: false }
          - { label: "CTA Button Link", name: "cta_button_link", widget: "string", required: false }